### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: JSON integer 20170415000 is too large or small for an Int32

### ISSUE THREAD

**Issue by Bluscream** [VRChatAPI/VRCAPIdotNet#4]
```
[@avatars/]Status: OK --- OK
avtr_aea7afac-afa8-443c-9a35-95c4db5da41c
Grabbed Avatar: ' Miko Ss ' made by Light ???

{
  "id": "avtr_aea7afac-afa8-443c-9a35-95c4db5da41c",
  "name": "Miko Ss",
  "description": "Miko Ss",
  "authorId": "usr_52120e25-89f2-4c39-a84f-280f24ef4bc5",
  "authorName": "Light ???",
  "tags": [],
  "assetUrl": "https://api.vrchat.cloud/api/1/file/file_ded215a6-c1c6-452e-b5f4-e4dc328b0a46/1/file",
  "imageUrl": "https://api.vrchat.cloud/api/1/file/file_118398ef-c6f6-46b6-8665-548d692724b8/1/file",
  "thumbnailImageUrl": "https://files.vrchat.cloud/thumbnails/2056728133.thumbnail-500.png",
  "releaseStatus": "public",
  "version": 4,
  "featured": false,
  "unityPackages": [
    {
      "id": "unp_fffefbd2-fb92-4e6a-8a77-e42efb74b444",
      "assetUrl": "https://api.vrchat.cloud/api/1/file/file_ded215a6-c1c6-452e-b5f4-e4dc328b0a46/1/file",
      "pluginUrl": null,
      "unityVersion": "5.6.3p1",
      "unitySortNumber": 50603010,
      "assetVersion": 1,
      "platform": "standalonewindows",
      "created_at": "2018-09-19T11:45:48.599Z"
    }
  ],
  "unityPackageUpdated": false,
  "unityPackageUrl": ""
}
[@avatars/]Status: OK --- OK
Newtonsoft.Json.JsonReaderException: JSON integer 20170415000 is too large or small for an Int32. Path 'unityPackages[1].unitySortNumber', line 1, position 1252.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at VRCAPIdotNet.VRCAPI.Endpoints.Universal.<GET>d__0`1.MoveNext() in C:\Users\blusc\source\repos\VRChat\Tools\VRCAPIdotNet\VRCAPIdotNet\VRCAPI\Endpoints\Universal.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VRCAPIdotNet.VRCAPI.Endpoints.Avatars.<GetSingle>d__0.MoveNext() in C:\Users\blusc\source\repos\VRChat\Tools\VRCAPIdotNet\VRCAPIdotNet\VRCAPI\Endpoints\Avatars.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at AviFav__Converter.Program.<MainAsync>d__6.MoveNext()
[@avatars/]Status: OK --- OK
avtr_157f6240-dc13-43ee-840d-8e097bf3a7f7
```

**Comment by ariesclark** [comment]
This isn't maintained right now, feel free to create a PR if you wish to patch or update it.
